/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoyOtherRouteImport } from './routes/yoy-other'
import { Route as YoyRouteImport } from './routes/yoy'
import { Route as PurchasePathRouteImport } from './routes/purchase-path'
import { Route as ProductsYoyRouteImport } from './routes/products-yoy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductFlowRouteImport } from './routes/product-flow'
import { Route as AttributionRouteImport } from './routes/attribution'
import { Route as IndexRouteImport } from './routes/index'

const YoyOtherRoute = YoyOtherRouteImport.update({
  id: '/yoy-other',
  path: '/yoy-other',
  getParentRoute: () => rootRouteImport,
} as any)
const YoyRoute = YoyRouteImport.update({
  id: '/yoy',
  path: '/yoy',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasePathRoute = PurchasePathRouteImport.update({
  id: '/purchase-path',
  path: '/purchase-path',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsYoyRoute = ProductsYoyRouteImport.update({
  id: '/products-yoy',
  path: '/products-yoy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductFlowRoute = ProductFlowRouteImport.update({
  id: '/product-flow',
  path: '/product-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributionRoute = AttributionRouteImport.update({
  id: '/attribution',
  path: '/attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attribution': typeof AttributionRoute
  '/product-flow': typeof ProductFlowRoute
  '/products': typeof ProductsRoute
  '/products-yoy': typeof ProductsYoyRoute
  '/purchase-path': typeof PurchasePathRoute
  '/yoy': typeof YoyRoute
  '/yoy-other': typeof YoyOtherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attribution': typeof AttributionRoute
  '/product-flow': typeof ProductFlowRoute
  '/products': typeof ProductsRoute
  '/products-yoy': typeof ProductsYoyRoute
  '/purchase-path': typeof PurchasePathRoute
  '/yoy': typeof YoyRoute
  '/yoy-other': typeof YoyOtherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attribution': typeof AttributionRoute
  '/product-flow': typeof ProductFlowRoute
  '/products': typeof ProductsRoute
  '/products-yoy': typeof ProductsYoyRoute
  '/purchase-path': typeof PurchasePathRoute
  '/yoy': typeof YoyRoute
  '/yoy-other': typeof YoyOtherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attribution'
    | '/product-flow'
    | '/products'
    | '/products-yoy'
    | '/purchase-path'
    | '/yoy'
    | '/yoy-other'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attribution'
    | '/product-flow'
    | '/products'
    | '/products-yoy'
    | '/purchase-path'
    | '/yoy'
    | '/yoy-other'
  id:
    | '__root__'
    | '/'
    | '/attribution'
    | '/product-flow'
    | '/products'
    | '/products-yoy'
    | '/purchase-path'
    | '/yoy'
    | '/yoy-other'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttributionRoute: typeof AttributionRoute
  ProductFlowRoute: typeof ProductFlowRoute
  ProductsRoute: typeof ProductsRoute
  ProductsYoyRoute: typeof ProductsYoyRoute
  PurchasePathRoute: typeof PurchasePathRoute
  YoyRoute: typeof YoyRoute
  YoyOtherRoute: typeof YoyOtherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yoy-other': {
      id: '/yoy-other'
      path: '/yoy-other'
      fullPath: '/yoy-other'
      preLoaderRoute: typeof YoyOtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoy': {
      id: '/yoy'
      path: '/yoy'
      fullPath: '/yoy'
      preLoaderRoute: typeof YoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-path': {
      id: '/purchase-path'
      path: '/purchase-path'
      fullPath: '/purchase-path'
      preLoaderRoute: typeof PurchasePathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products-yoy': {
      id: '/products-yoy'
      path: '/products-yoy'
      fullPath: '/products-yoy'
      preLoaderRoute: typeof ProductsYoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-flow': {
      id: '/product-flow'
      path: '/product-flow'
      fullPath: '/product-flow'
      preLoaderRoute: typeof ProductFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attribution': {
      id: '/attribution'
      path: '/attribution'
      fullPath: '/attribution'
      preLoaderRoute: typeof AttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttributionRoute: AttributionRoute,
  ProductFlowRoute: ProductFlowRoute,
  ProductsRoute: ProductsRoute,
  ProductsYoyRoute: ProductsYoyRoute,
  PurchasePathRoute: PurchasePathRoute,
  YoyRoute: YoyRoute,
  YoyOtherRoute: YoyOtherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
